### ISSUE TITLE
Command.timings is not compatible with spigot

### ISSUE THREAD

**Issue by Paulomart** [GlowstonePlusPlus/Glowkit-Legacy#10]
Hello,

I currently issues with the `timings` field in `org.bukkit.command.Command`. Its used to measure timings of commands.

In spigot it has the type `org.spigotmc.CustomTimingsHandler`. On current glowkit is has the type `co.aikar.timings.Timing`. Im sure this because there is no org.spigot package in glowkit, but should it be moved to ensure compatibly with plugins?

**Comment by Paulomart** [comment]
Also: If a plugin uses the CustomTimingsHandler it will not work in glowstone++

**Comment by mastercoms** [comment]
I thought you could still use CustomTimingsHandler. I will look into it.

**Comment by Paulomart** [comment]
Thanks, tell me if you need a pr

**Comment by mastercoms** [comment]
If you have a fix in mind already, please go ahead and make a PR, please.

**Comment by Paulomart** [comment]
I dont know, moving everything in org.spigotmc.timings seems bad

**Comment by Paulomart** [comment]
Is it possible, that our timings version is newer than in spigot? Maybe they will update too?

**Comment by mastercoms** [comment]
Yes, we recently just upgraded to timings v2. I read there was supposed to be legacy support but maybe I merged something incorrectly.

**Comment by mastercoms** [comment]
Are there any problems with this file? https://github.com/GlowstonePlusPlus/Glowkit/blob/bukkit%2Bglowkit/src/main/java/org/spigotmc/CustomTimingsHandler.java
