### ISSUE TITLE
Upstream merge

### ISSUE THREAD

**Issue by mastercoms** [GlowstonePlusPlus/Glowkit-Legacy#3]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/b333b58c05a0392f3fcf825028c058518a50d1c7

I don't have my dev environment setup so I would rather not do this merge.

**Comment by jimmikaelkael** [comment]
@mastercoms I don't understand what you mean... Do you you need some help to test this ?

**Comment by mastercoms** [comment]
I meant that there was a change to Bukkit upstream, and I wanted someone to merge Bukkit upstream to Glowkit. However, this issue has been long irrelevant, as I have been merging from upstream, but I forgot to close the issue until now.

**Comment by jimmikaelkael** [comment]
@mastercoms my bad, I was tired when I've read your post above as I believed it was a fresh comment...
